import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { IOrg } from "../../interfaces";
import styles from "./Organizacao.module.scss";

const Organizacao: NextPage = () => {
  const [organizacao, setOrganizacao] = useState<IOrg>();
  const router = useRouter();
  useEffect(() => {
    if (!router.query.id) return;

    const getOrganizacao = async () => {
      const res = await axios.post("/api/get-org", {
        id: Number(router.query.id),
      });

      setOrganizacao(res.data[0]);
    };

    getOrganizacao();
  }, [router.query.id]);

  return (
    <div className={styles.container}>
      <Head>
        <title>{organizacao?.nome}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.nome}>{organizacao?.nome}</div>
        <div>Ano de fundação: {organizacao?.ano_fundacao.substring(0, 10)}</div>
        <div>Cnpj: {organizacao?.cnpj}</div>
      </main>
    </div>
  );
};

export default Organizacao;
