import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { IJogador } from "../../interfaces";
import styles from "./Jogador.module.scss";

const Jogador: NextPage = () => {
  const [jogador, setJogador] = useState<IJogador>();
  const router = useRouter();
  useEffect(() => {
    if (!router.query.id) return;

    const getJogador = async () => {
      const res = await axios.post("/api/get-jogador", {
        id: Number(router.query.id),
      });

      setJogador(res.data[0]);
    };

    getJogador();
  }, [router.query.id]);

  return (
    <div className={styles.container}>
      <Head>
        <title>{jogador?.nome}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.nome}>{jogador?.nome}</div>
        <div>Nacionalidade: {jogador?.nacionalidade}</div>
        <div>Data de Nascimento: {jogador?.data_nasc}</div>
        <div>Gênero: {jogador?.genero}</div>
        <div>Valor de Passe: {jogador?.valor_passe}</div>
        <div>
          Time participante: {jogador?.time ? jogador.time : "Sem time"}
        </div>
      </main>
    </div>
  );
};

export default Jogador;
