import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ITime } from "../../interfaces";
import styles from "./Times.module.scss";

const Times: NextPage = () => {
  const [data, setData] = useState<ITime[]>([]);
  const [search, setSearch] = useState("");

  const filteredJogadores = search.length
    ? data.filter((jogador) =>
        jogador.nome.toLowerCase().includes(search.toLowerCase())
      )
    : data;

  useEffect(() => {
    const getData = async () => {
      const res = await axios.post("/api/get-times", {});

      setData(res.data);
    };

    getData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Times</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <h1>Times</h1>
          <input
            type="text"
            placeholder="Pesquisar..."
            onChange={(e) => {
              setSearch(e.target.value);
            }}
          />
        </div>

        <div className={styles.list}>
          {search.length
            ? filteredJogadores.map((time) => (
                <Link key={time.id_time} href={`time/${time.id_time}`}>
                  <div className={styles.item}>
                    <div className={styles.item__name}>{time.nome}</div>
                    <div className={styles.item__org}>{time.modalidade}</div>
                  </div>
                </Link>
              ))
            : data.map((time) => (
                <Link key={time.id_time} href={`time/${time.id_time}`}>
                  <div className={styles.item}>
                    <div className={styles.item_name}>{time.nome}</div>
                    <div className={styles.item_org}>{time.modalidade}</div>
                  </div>
                </Link>
              ))}
        </div>
      </main>
    </div>
  );
};

export default Times;
