import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { IJogador, IOrg } from "../../interfaces";
import styles from "./Organizacoes.module.scss";

const Organizacoes: NextPage = () => {
  const [data, setData] = useState<IOrg[]>([]);
  const [search, setSearch] = useState("");

  const filteredData = search.length
    ? data.filter((org) =>
        org.nome.toLowerCase().includes(search.toLowerCase())
      )
    : data;

  useEffect(() => {
    const getData = async () => {
      const res = await axios.post("/api/get-orgs", {});

      setData(res.data);
    };

    getData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Organizações</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <h1>Organizações</h1>
          <input
            type="text"
            placeholder="Pesquisar..."
            onChange={(e) => {
              setSearch(e.target.value);
            }}
          />
        </div>

        <div className={styles.list}>
          {search.length
            ? filteredData.map((org) => (
                <div key={org.id_org} className={styles.item}>
                  <Link href={`org/${org.id_org}`}>
                    <>
                      <div className={styles.item__name}>{org.nome}</div>
                      <div className={styles.item__org}>
                        Data de fundação: {org.ano_fundacao.substring(0, 10)}
                      </div>
                    </>
                  </Link>
                </div>
              ))
            : data.map((org) => (
                <Link key={org.id_org} href={`org/${org.id_org}`}>
                  <div className={styles.item}>
                    <div className={styles.item_name}>{org.nome}</div>
                    <div className={styles.item_org}>
                      Data de fundação: {org.ano_fundacao.substring(0, 10)}
                    </div>
                  </div>
                </Link>
              ))}
        </div>
      </main>
    </div>
  );
};

export default Organizacoes;
