import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { IModalidade } from "../../interfaces";
import styles from "./Modalidade.module.scss";

const Modalidade: NextPage = () => {
  const [modalidade, setModalidade] = useState<IModalidade>();
  const router = useRouter();
  useEffect(() => {
    if (!router.query.id) return;

    const getModalidade = async () => {
      const res = await axios.post("/api/get-modalidade", {
        id: Number(router.query.id),
      });

      setModalidade(res.data[0]);
    };

    getModalidade();
  }, [router.query.id]);

  return (
    <div>
      <Head>
        <title>TIPO: {modalidade?.tipo}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>TIPO: {modalidade?.tipo}</div>
      </main>
    </div>
  );
};

export default Modalidade;
