import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ICampeonato } from "../../interfaces";
import styles from "./Campeonatos.module.scss";

const Campeonatos: NextPage = () => {
  const [data, setData] = useState<ICampeonato[]>([]);
  const [search, setSearch] = useState("");

  const filteredData = search.length
    ? data.filter((camp) =>
        camp.nome.toLowerCase().includes(search.toLowerCase())
      )
    : data;

  useEffect(() => {
    const getData = async () => {
      const res = await axios.post("/api/get-campeonatos", {});
      setData(res.data);
    };

    getData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Campeonatos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <h1>Disputas</h1>
          <input
            type="text"
            placeholder="Pesquisar..."
            onChange={(e) => {
              setSearch(e.target.value);
            }}
          />
        </div>

        <div className={styles.list}>
          {search.length
            ? filteredData.map((camp) => (
                <Link key={camp.id_camp} href={`campeonato/${camp.id_camp}`}>
                  <div className={styles.item}>
                    <div className={styles.item__name}>{camp.nome}</div>
                    <div className={styles.item__org}>
                      {camp.data_camp.substring(0, 10)}
                    </div>
                    <div className={styles.item__org}>{camp.modalidade}</div>
                  </div>
                </Link>
              ))
            : data.map((camp) => (
                <Link key={camp.id_camp} href={`campeonato/${camp.id_camp}`}>
                  <div className={styles.item}>
                    <div className={styles.item_name}>{camp.nome}</div>
                    <div className={styles.item_data}>
                      {camp.data_camp.substring(0, 10)}
                    </div>
                    <div className={styles.item__org}>{camp.modalidade}</div>
                  </div>
                </Link>
              ))}
        </div>
      </main>
    </div>
  );
};

export default Campeonatos;
