import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { ICampeonato } from "../../interfaces";
import styles from "./Campeonato.module.scss";

const Campeonato: NextPage = () => {
  const [campeonato, setCampeonato] = useState<ICampeonato>();
  const router = useRouter();
  useEffect(() => {
    if (!router.query.id) return;

    const getCampeonato = async () => {
      const res = await axios.post("/api/get-campeonato", {
        id: Number(router.query.id),
      });

      setCampeonato(res.data[0]);
    };

    getCampeonato();
  }, [router.query.id]);

  return (
    <div className={styles.container}>
      <Head>
        <title>{campeonato?.nome}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.nome}>{campeonato?.nome}</div>
        <div className={styles.modalidade}>{campeonato?.modalidade}</div>
        <div className={styles.premiacao}>
          Premiação: {campeonato?.premiacao}
        </div>
        <div className={styles.qntd}>
          Quantidade de times {campeonato?.qnt_times}
        </div>
        <div className={styles.data}>
          Data: {campeonato?.data_camp.substring(0, 10)}
        </div>
      </main>
    </div>
  );
};

export default Campeonato;
