import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { ITime } from "../../interfaces";
import styles from "./Time.module.scss";

const Time: NextPage = () => {
  const [time, setTime] = useState<ITime>();
  const router = useRouter();
  useEffect(() => {
    if (!router.query.id) return;

    const getTime = async () => {
      const res = await axios.post("/api/get-time", {
        id: Number(router.query.id),
      });

      setTime(res.data[0]);
    };

    getTime();
  }, [router.query.id]);

  return (
    <div className={styles.container}>
      <Head>
        <title>{time?.nome}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.nome}>{time?.nome}</div>
        <div>Modalidade: {time?.modalidade}</div>
        <div>Quantidade de titulos: {time?.qnt_titulos}</div>
        <div>Org: {time?.org}</div>
      </main>
    </div>
  );
};

export default Time;
