import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import { IJogador } from "../../interfaces";
import styles from "./Jogadores.module.scss";

const Jogadores: NextPage = () => {
  const [jogadores, setJogadores] = useState<IJogador[]>([]);
  const [search, setSearch] = useState("");

  const filteredJogadores = search.length
    ? jogadores.filter((jogador) =>
        jogador.nome.toLowerCase().includes(search.toLowerCase())
      )
    : jogadores;

  useEffect(() => {
    const getJogadores = async () => {
      const res = await axios.post("/api/get-jogadores");

      setJogadores(res.data);
    };

    getJogadores();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Jogadores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <h1>Jogadores</h1>
          <input
            type="text"
            placeholder="Pesquisar..."
            onChange={(e) => {
              setSearch(e.target.value);
            }}
          />
        </div>

        <div className={styles.list}>
          {search.length
            ? filteredJogadores.map((jogador) => (
                <div key={jogador.id_jogador} className={styles.item}>
                  <Link href={`jogador/${jogador.id_jogador}`}>
                    <>
                      <div className={styles.item__name}>{jogador.nome}</div>
                      <div className={styles.item__org}>
                        {jogador.nacionalidade}
                      </div>
                      <div className={styles.item__org}>{jogador.time}</div>
                    </>
                  </Link>
                </div>
              ))
            : jogadores.map((jogador) => (
                <Link
                  key={jogador.id_jogador}
                  href={`jogador/${jogador.id_jogador}`}
                >
                  <div className={styles.item}>
                    <div className={styles.item_name}>{jogador.nome}</div>
                    <div className={styles.item_org}>
                      {jogador.nacionalidade}
                    </div>
                    <div className={styles.item__org}>{jogador.time}</div>
                  </div>
                </Link>
              ))}
        </div>
      </main>
    </div>
  );
};

export default Jogadores;
